# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M9KEPyLQ2zDThiBgNpd-siZfiLp1jYUj
"""

import streamlit as st
import pandas as pd
import joblib
from sklearn.base import BaseEstimator, TransformerMixin

# ⛑️ Tambahkan class Winsorizer di awal
class Winsorizer(BaseEstimator, TransformerMixin):
    def __init__(self, lower=0.01, upper=0.99):
        self.lower = lower
        self.upper = upper

    def fit(self, X, y=None):
        import pandas as pd
        if not isinstance(X, pd.DataFrame):
            X = pd.DataFrame(X)
        self.lower_bounds_ = X.quantile(self.lower)
        self.upper_bounds_ = X.quantile(self.upper)
        return self

    def transform(self, X):
        import pandas as pd
        if not isinstance(X, pd.DataFrame):
            X = pd.DataFrame(X)
        return X.clip(self.lower_bounds_, self.upper_bounds_, axis=1)

# ✅ Setelah class sudah di-declare, baru load
preprocessor = joblib.load("preprocessor.pkl")
model = joblib.load("model_fuel.pkl")