# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M9KEPyLQ2zDThiBgNpd-siZfiLp1jYUj
"""

import streamlit as st
import pandas as pd
import joblib

# =====================================
# LOAD MODEL & PREPROCESSOR
# =====================================
model = joblib.load("model_fuel.pkl")
preprocessor = joblib.load("preprocessor.pkl")  # Hasil dari fit di training!

# =====================================
# APLIKASI STREAMLIT
# =====================================
st.title("🚗 Prediksi Biaya Bahan Bakar Tahunan (Indonesia)")

st.write("Masukkan data kendaraan kamu untuk memprediksi estimasi biaya bahan bakar tahunan dalam Rupiah.")

# INPUT PENGGUNA
year = st.number_input("Tahun Kendaraan", min_value=1980, max_value=2025, value=2015)
engine_cylinders = st.selectbox("Jumlah Silinder Mesin", options=[2, 3, 4, 5, 6, 8], index=2)
engine_displacement = st.number_input("Kapasitas Mesin (Liter)", min_value=0.5, max_value=10.0, value=2.0, step=0.1)
fuel_type = st.selectbox("Jenis Bahan Bakar", options=["Regular", "Premium", "Diesel", "Electricity"])
vehicle_class = st.selectbox("Kelas Kendaraan", options=["Compact", "SUV", "Sedan", "Pickup", "Minivan"])

# BENTUK DATAFRAME
input_df = pd.DataFrame({
    "year": [year],
    "engine_cylinders": [engine_cylinders],
    "engine_displacement": [engine_displacement],
    "fuel_type": [fuel_type],
    "vehicle_class": [vehicle_class]
})

# =====================================
# PROSES PREDIKSI
# =====================================
if st.button("🔍 Prediksi Biaya BBM"):
    try:
        # Transformasi sesuai pipeline training
        input_transformed = preprocessor.transform(input_df)

        # Prediksi
        pred = model.predict(input_transformed)[0]
        st.success(f"💰 Estimasi Biaya BBM Tahunan: **Rp {pred:,.0f}**")
    except Exception as e:
        st.error(f"Terjadi kesalahan saat prediksi: {e}")